PACKAGE_NAME="oxp3-hid-rgb"
PACKAGE_VERSION="0.1.0"
BUILT_MODULE_NAME[0]="hid-oxp"
DEST_MODULE_LOCATION[0]="/updates/dkms"
AUTOINSTALL="yes"
MAKE[0]="make -C /lib/modules/${kernelver}/build M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build modules"
